baseurl = "https://www.dutchcloudmeetup.online"
title = "Dutch Cloud Meetup"
theme = "hugo-universal-theme"
languageCode = "en-us"
defaultContentLanguage = "en"
googleAnalytics = "G-6WYFV491HQ"
summaryLength = 70
paginate = 10
buildFuture = true

[menu]
# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Events"
    identifier = "menu.events"
    url        = "/events/"
    weight     = 5

[[menu.main]]
    identifier = "menu.sponsors"
    name       = "Sponsors"
    url        = "/sponsors/"
    weight     = 6

[[menu.main]]
    identifier = "menu.speakers"
    name       = "CFP"
    url        = "/CFP/"
    weight     = 7

[[menu.main]]
    identifier = "menu.code"
    name       = "Code of Conduct"
    url        = "/codeofconduct/"
    weight     = 8

[[menu.main]]
    identifier = "team"
    name       = "Team"
    url        = "/team/"
    weight     = 9

[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 10

# Top bar social links menu
[[menu.topbar]]
    weight = 3
    name = "LinkedIn"
    url = "https://www.linkedin.com/company/dutch-cloud-meetup/"
    pre = "<i class='fab fa-2x fa-linkedin'></i>"

[[menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "http://twitter.com/dutchcloudmeetup"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "YouTube"
    url = "https://www.youtube.com/channel/UC5rlNwGCsECDGQrHgrxG3Pg"
    pre = "<i class='fab fa-2x fa-youtube'></i>"

[params]
    viewMorePostLink = "/events/"
    author = "Dutch Cloud Meetup"
    defaultKeywords = ["dutch cloud meetup", "cloud", "Azure"]
    mainSections = ["events"]
    defaultDescription = "Dutch Cloud Meetup - The Cloud Meetup group of the Netherlands"

    # Social media
    twitter_site = "dutchcloudmeetup"
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    contact_form_ajax = true

    #forms
    subscribe_action = "https://prod-213.westeurope.logic.azure.com:443/workflows/5ddb24fd6e264a43b4f4c8ad40a38bc6/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=JBaXgNQQ282jIUkDMb7rdxfcijdWi6rAhdH3oCGpHEw"
    contact_action = "https://prod-222.westeurope.logic.azure.com:443/workflows/4e35983811e24776a28915ed460c36d8/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=VLpCMWNgdyMPlsavm2rrs1OE130rc1z2muKDqy-UZmY"

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "6LfaxtohAAAAAELRkS4CT4Dm0SPlc6Ttr4e48xIJ"

    about_us = "<p>The Dutch Cloud Meetup is a user group that focuses on Cloud Technologies. The group was founded in 2018 by an IT enthusiast who found the number of user group meetings in the Rotterdam area (South Holland) was too low.</p>"
    copyright = "Copyright (c) 2022, Dutch Cloud Meetup; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    disabled_logo = false
    logo_text = "Dutch Cloud Meetup"

    logo = "img/logo-small.png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"
  

[permalinks]
    events = "/events/:year/:month/:day/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true

# Enable and disable widgets for the right sidebar
[params.widgets]
    tags = true
    search = true

[params.carouselCustomers]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonals]
    items = 3
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000


[params.testimonials]
    enable = true
    title = "Team"
    subtitle = ""

[params.team]
    enable = true
    title = "Team"
    subtitle = ""

[params.see_more]
    enable = true
    icon = "far fa-bell"
    title = "Our Next Event"
    subtitle = "November 8th - A Evening on Cloud Security"
    link_url = "events/2022/11/08/"
    link_text = "Information / Register"

[params.clients]
    enable = true
    title = "Sponsors"
    subtitle = ""

[params.sponsors]
    enable = true
    title = "Sponsors"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"