# This is a basic workflow to help you get started with Actions

name: Website CI/CD
on:
  push:
    branches: main

  workflow_dispatch:

env:
  archName: Website
  archFolder: './webiste/public/'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.88.1'
          extended: true

      - name: Build
        run: |
          cd website
          hugo
      - name: Archive production website
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.archName}}
          path: ${{env.archFolder}}
